### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by memcpy1337** [elraccoone/react-unity-webgl#178] opened 2021-04-16 06:46 UTC
I am trying to put webgl into one of the pages of my react app.
Here i my simple component:

```
import React from "react";
import Unity, { UnityContext } from "react-unity-webgl";

const unityContext = new UnityContext({
  loaderUrl: "Build/new.loader.js",
  dataUrl: "Build/new.data",
  frameworkUrl: "Build/new.framework.js",
  codeUrl: "Build/new.wasm",
});

export const Minesweeper = () => {
  return <Unity unityContext={unityContext} />;
};
```

But when page loaded, i got 2 errors:
![Screenshot_18](https://user-images.githubusercontent.com/54195483/114983207-ac3e8a80-9ed3-11eb-8ec6-1b7387f07eac.png)

I am trying this:

1. In webgl build settings `Compression Format: disabled`
2. In webgl build settings `Decompression Fallback: true`

But it did not help

new.loader.js: https://pastebin.com/m2sPgv8h

My folders structure:
![Screenshot_17](https://user-images.githubusercontent.com/54195483/114982736-2d495200-9ed3-11eb-9e66-b6e7e5b87231.png)

**Comment by memcpy1337** [comment] 2021-04-16 07:12
Move "Build" folder to /public didnt help

**Comment by jeffreylanters** [comment] 2021-04-16 08:15
Duplicate of #57

**Closed by jeffreylanters** 2021-04-16 08:15 UTC
