### ISSUE TITLE
Unexpected token '<'

### ISSUE THREAD

**Issue by Loque18** [elraccoone/react-unity-webgl#134] opened 2020-11-25 05:59 UTC
Hi! I know this is a very know issue but for some reason I can't get it to work, I've moved my build folder to public path, and stills throwing the same error 

**Screenshots**

this is my code
![image](https://user-images.githubusercontent.com/28642447/100188787-f4bfc200-2eb8-11eb-8b0f-870ba2ddfe32.png)

and here is my build folder
![image](https://user-images.githubusercontent.com/28642447/100188869-2173d980-2eb9-11eb-87ea-467797118fce.png)

**Details **
 - React Unity WebGL Version:  8.0.0
 - Browser: chrome
 - NodeJS Version: e.g. 10.16.3
- Unity Version: 2020

I would appreciate your help, Thanks :) !

**Comment by jeffreylanters** [comment] 2020-11-25 11:04
Duplicate of #57

**Closed by jeffreylanters** 2020-11-25 11:04 UTC

**Comment by Loque18** [comment] 2020-11-25 20:06
Thanks for your fast repply Jeffrey! 

it looks like it was the path now it looks like this

![image](https://user-images.githubusercontent.com/28642447/100276379-6d616580-2f2f-11eb-9324-de98d662288b.png)

and the solution was to change the URL 
![image](https://user-images.githubusercontent.com/28642447/100276424-81a56280-2f2f-11eb-88c2-c49dd34c8065.png)

I had to install react-unity-webgl-test to ensure that it wasn't some weird error with my react version or something like that, and I finally got it to work, thanks again!

**Comment by jeffreylanters** [comment] 2020-11-25 21:04
Hi Loque, I'm glad it resolved your issue. Happy coding and best of luck with your project!

**Comment by ClydeFrog04** [comment] 2021-02-22 14:38
@Loque18 Did you put the index.html from the unity build in your project somewhere? I am getting this same issue but can't work it out. I see you have the index.html provided by react but what about the one made by the unity build?

**Comment by Loque18** [comment] 2021-02-22 15:29
> @Loque18 Did you put the index.html from the unity build in your project somewhere? I am getting this same issue but can't work it out. I see you have the index.html provided by react but what about the one made by the unity build?

Hi! The index generated by unity is not needed, you manage the unity built with the react component provided with this package, hope it helps you

**Comment by ClydeFrog04** [comment] 2021-02-22 15:44
Thanks! It doesn't solve my issue, but it is good to know. I tried a build without compressing to make sure that wasn't messing with things and still no luck :/ I have my file system set up just like yours as far as I can tell

**Comment by Loque18** [comment] 2021-02-23 14:23
@ClydeFrog04 it's the same that I got, make sure your unity generated files are in the public folder and also make sure the path to the folder is right

**Comment by ClydeFrog04** [comment] 2021-02-24 05:39
I had them in the public folder, the problem was my build folder was name "Build" and not "build" and it works now!
