### ISSUE TITLE
Regularly mounting, unmounting, and remounting eventually crashes the page

### ISSUE THREAD

**Issue by rivertam** [elraccoone/react-unity-webgl#61] opened 2019-04-10 01:19 UTC
**Describe the bug**

If you have an instance of `Unity` and mount, unmount, and remount it due to state conditions changing, the page eventually crashes. I've only tested in Chrome 72.0.3626.81 on GNU/Linux, so it may not be browser independent. If this is a usecase you plan on supporting, I can do more research into other browsers as well as perhaps some profiling.

**To Reproduce**
- Have a component that just renders a `Unity`.
  - It's exactly like the sample from the README, except `unityContent` is `static`
- Unmount and remount that component many times
- Eventually, the page crashes

If this is a usecase you plan on supporting, I will look into creating an MVP. It's somewhat harder for me as I don't have a Unity build chain, but I can try to find a stand-in project and see if I can reproduce.

**Expected behavior**
I believe it is currently leaking resources somehow.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome 
 - Version: 72.0.3626.81 

**Additional context**
I understand if you're not planning on supporting this usecase, as I understand most people don't use Unity in particularly dynamic contexts. I may just use this issue to describe my solution in case someone else wants help. Thanks for the library!

**Comment by jeffreylanters** [comment] 2019-04-10 08:10
Duplicate of #22

**Closed by jeffreylanters** 2019-04-10 08:10 UTC

**Comment by jeffreylanters** [comment] 2019-04-10 15:22
@rivertam no problem at all, thanks for reporting!
