### ISSUE TITLE
Console error when trying to use .gz files from Unity 2020 WebGL build

### ISSUE THREAD

**Issue by motiondirector** [elraccoone/react-unity-webgl#122] opened 2020-09-17 21:14 UTC
I'm getting console error below when trying to use .gz files:
`webGL_build_unity2020.framework.js.gz:1 Uncaught SyntaxError: Invalid or unexpected token`

This is how I'm trying to use them in UnityContext constructor. 

````
const WEBGL_BUILD = 'webGL_build_unity2020';

...
    unityContext: new UnityContext({
        loaderUrl: `./${WEBGL_BUILD}/Build/${WEBGL_BUILD}.loader.js`,
        dataUrl: `./${WEBGL_BUILD}/Build/${WEBGL_BUILD}.data.gz`,
        frameworkUrl: `./${WEBGL_BUILD}/Build/${WEBGL_BUILD}.framework.js.gz`,
        codeUrl: `./${WEBGL_BUILD}/Build/${WEBGL_BUILD}.wasm.gz`
    }),
...
````
Can I use .gz files on UnityContext if having the server configured for gzip compression?

**Comment by jeffreylanters** [comment] 2020-09-18 07:33
Gzipping is off-topic for this module, if you cannot configure your server you can create a compressionless build. Unexpected token is a duplicate of #57

**Closed** 2020-09-22 21:54 UTC

**Comment by sd63534790** [comment] 2021-01-29 01:41
I set nginx gzip and application/wasm type, But it didn't work,Please help me.
![1611884343(1)](https://user-images.githubusercontent.com/5291257/106220259-11101000-6216-11eb-8a55-1187c92a6efc.png)
