### ISSUE TITLE
Unexpected token <in JSON position 0

### ISSUE THREAD

**Issue by Syndicist** [elraccoone/react-unity-webgl#91] opened 2020-02-29 15:23 UTC
To preface all this, I'm brand new to react, so I apologize if this is more obvious than I can see it.

I can't seem to launch the exported WebGL project through React. I get this error in the console when I try:
![image](https://user-images.githubusercontent.com/31106886/75610145-8e9a4000-5adc-11ea-93c0-432f927d376b.png)

I've been looking through other, similar issues but as far as I can tell I'm following all procedures to the letter. My App.js unity content section looks like this:
`
    this.unityContent = new UnityContent(
      "MyGame/Build/Build.json",
      "MyGame/Build/UnityLoader.js"
`
These are both in public/MyGame/Build. Moving to /public/Build and making the corresponding changes doesn't do anything as one would expect. index.html is of course in /public.

I appreciate any and all help on this.

**Comment by jeffreylanters** [comment] 2020-03-01 16:58
Duplicate of #57

**Closed by jeffreylanters** 2020-03-01 16:58 UTC
