### ISSUE TITLE
Problem with webpack and react

### ISSUE THREAD

**Issue by robertobrogi** [elraccoone/react-unity-webgl#68] opened 2019-06-25 15:46 UTC
**Describe the bug**

Impossible to load a unity canvas:

![image](https://user-images.githubusercontent.com/34241295/60112682-85e4b380-9770-11e9-9c88-68dc5752373b.png)

**Desktop (please complete the following information):**
 - Browser [chrome, Firefox]

**Additional context**
we used webpack cli:
    "webpack": "^4.15.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4"

in webpack we have:

new CopyWebpackPlugin([
        {from:'src/assets',to:'assets'},
        {from:'src/skins',to:'skins'},
        {from:'src/images',to:'images'},
        {from:'src/fonts',to:'fonts'},
        {from:'src/i18n',to:'i18n'},
        {from:'src/webGL',to:'webGL'}
    ])

in our structure we have:

scr/webGL

inside:
Build/  
TemplatesData
index.html

and this init component:

`this.unityContent = new UnityContent(
      "webGL/Build/webGl.json",
      "webGL/Build/UnityLoader.js"
    );`

whats wrong!??! there is a webpack problem?

we don't have  a public folder....

`output: {
    filename: 'main.js',
    path: path.resolve(__dirname, '..', 'dist'),
    publicPath: '/'
    // necessary for HMR to know where to load the hot update chunks
  },`

please help....

thanks a lot

**Comment by jeffreylanters** [comment] 2019-06-25 21:08
Looks like a duplicate of #31

**Comment by robertobrogi** [comment] 2019-06-26 07:53
@jeffreylanters is close for inactivity and there isn't a solution :(

**Comment by jeffreylanters** [comment] 2019-06-26 08:07
The error `Unexpected token <` occurs when the browsers tries to run a 404 page as JavaScript. That is where the token `<` comes from, a not found response such as a 404 page is very likely to start with `<html...`.

The path you pass to the source and loader are relative to your html file. When using a constructor like:

```js
this.unityContent = new UnityContent(
  "MyGame/Build.json",
  "MyGame/UnityLoader.js"
);
```

Your structure should look something like:

```
|- index.html
|- ....
\- MyGame
    |- Build.json
    \- UnityLoader.js
```

I hope this makes the implemention a little bit more clear.

**Comment by robertobrogi** [comment] 2019-06-26 08:17
Thanks for reply.

I have the same configuration..... in dev not loading the unity view end with a dist folder i have another problem
see my dist folder

![image](https://user-images.githubusercontent.com/34241295/60163216-6fd00500-97fb-11e9-962e-f77bc672c044.png)

exception thrown: TypeError: ReactUnityWebGL.SendPrenotation is not a function,TypeError: ReactUnityWebGL.SendPrenotation is not a function UnityLoader.js:4

**Comment by robertobrogi** [comment] 2019-06-26 13:07
ooooooooooo fix it...... was a error in webpack.....

the problem was here:

`devServer: {
    hot: true, // enable HMR on the server
    port: 3000,
    historyApiFallback: true,
    contentBase: path.resolve(__dirname, '..', 'src', 'scripts'), // match the output path
    publicPath: '/' // match the output `publicPath`
  },`

replace with:

`devServer: {
    hot: true, // enable HMR on the server
    port: 3000,
    historyApiFallback: true,
    contentBase: path.resolve(__dirname, '..', 'src'), // match the output path
    publicPath: '/' // match the output `publicPath`
  },`

and i have removed:

`new CopyWebpackPlugin([
        {from:'src/assets',to:'assets'},
        {from:'src/skins',to:'skins'},
        {from:'src/images',to:'images'},
        {from:'src/fonts',to:'fonts'},
        {from:'src/i18n',to:'i18n'},
        {from:'src/webGL',to:'webGL'}
    ])`

thanks a lot for the supprt

**Comment by jeffreylanters** [comment] 2019-06-26 15:14
Awesome! Have fun!

**Closed by jeffreylanters** 2019-06-26 15:14 UTC
