### ISSUE TITLE
Error when you set the app

### ISSUE THREAD

**Issue by garayco** [elraccoone/react-unity-webgl#63] opened 2019-05-22 16:12 UTC
**Describe the bug**

The problem is that I write everything necessary to show the build exported by unity and it does not appear. I just get an error

**To Reproduce**
1. Paste what's in the Quick Start Guide. Click on '....'
2. npm start
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/22529692/58190566-6bf01680-7c82-11e9-973b-aced81f46442.png)

![image](https://user-images.githubusercontent.com/22529692/58190607-85915e00-7c82-11e9-899a-611b866de7a2.png)

**Comment by jeffreylanters** [comment] 2019-05-23 13:21
'Unexpected token <' is thrown because the UnityLoader.js file was not found. Your browser returns an 404 page which starts with <html.... This is where the unexpected token comes from.

Duplicate of #31

**Closed** 2019-05-24 12:17 UTC
